### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './mixed_precision_scripts/optimize/tensor_ratio/sdxl_turbo/weight_ratio_config.yaml'

### ISSUE THREAD

**Issue by Flying-Cloud** [A-suozhang/MixDQ#7]
I cant find the weight_ratio_config.yaml under the tensor_ratio folder. Is that a oversight？

**Comment by stein-666** [comment]
> I cant find the weight_ratio_config.yaml under the tensor_ratio folder. Is that a oversight？

Thank you for your interest in our work! The file has been provided. Please pull the newest commit and check the directory `./mixed_precision_scripts/optimize/tensor_ratio/sdxl_turbo`.
